server:  servlet:    context-path: /api
spring:
  datasource:
    password: 1234
    username: root
    url: jdbc:mysql://localhost:3306/estacionamiento    driver-class-name: com.mysql.jdbc.Driver
  jpa:    hibernate:      ddl-auto: create    database-platform: org.hibernate.dialect.MySQL5Dialect        